version: "3.8"
services: 
  golim:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golim
    environment:
      - GOLIM_WEB_SERVER_ADDR=http://192.168.0.12:8000
      - GOLIM_SERVER_ADDR=0.0.0.0:8080
      - GOLIM_RATE_LIMITER_BURST=1
      - GOLIM_RATE_LIMITER_WINDOW_SECONDS=1
    ports:
      - "8080:8080"